CREATE TABLE STUDENT(
sid INT,
name VARCHAR(20),
dob VARCHAR(20),
pmark INT,
cmark INT,
mmark int);

DESCRIBE TABLE STUDENT;
INSERT INTO STUDENT (sid,name,dob,pmark,cmark,mmark) VALUES (1,'Sandra','29-07-99',75,83,88);
SELECT * FROM STUDENT;
INSERT INTO STUDENT VALUES(102,'Athira','15-06-99',70,76,85);
INSERT INTO STUDENT VALUES(103,'Roshmi','29-05-98',80,86,85);
INSERT INTO STUDENT VALUES(104,'Arathy','03-05-97',50,38,59);
INSERT INTO STUDENT VALUES(109,'Nisha','23-11-98',60,79,83);
UPDATE STUDENT 
SET sid=107 WHERE name='Athira';

SELECT sid,name FROM STUDENT WHERE dob=(SELECT MAX(dob) FROM STUDENT); 
SELECT  * FROM STUDENT WHERE mmark >=40 AND (pmark >=40 or cmark >=40);

ALTER TABLE STUDENT ADD total INT;
ALTER TABLE  STUDENT ADD average FLOAT(10,3);
DESCRIBE STUDENT;

SELECT name FROM STUDENT WHERE mmark=(SELECT max(mmark) FROM STUDENT);

select name from STUDENT where cmark=(select min(cmark) from STUDENT);

UPDATE STUDENT SET total=pmark+cmark+mmark;
select * from STUDENT;
UPDATE STUDENT SET average=total/3;

SELECT * FROM STUDENT ORDER BY total DESC;

ALTER TABLE STUDENT RENAME COLUMN average TO avg_mark;
SELECT * FROM STUDENT;

SELECT AVG(avg_mark) AS overall_average FROM STUDENT;
SELECT * FROM STUDENT WHERE total > (SELECT AVG(total) FROM STUDENT);

SELECT * FROM STUDENT WHERE avg_mark > (SELECT AVG(avg_mark) FROM STUDENT);

SELECT COUNT(*) FROM STUDENT WHERE AVG_MARK > (SELECT AVG(AVG_MARK) FROM STUDENT);


